### ISSUE TITLE
快看！！！

### ISSUE THREAD

**Issue by echo-hmwang** [PengXuanyao/learngit#1]
最好的git中文教程：https://www.liaoxuefeng.com/wiki/896043488029600

**Comment by PengXuanyao** [comment]
哈，谢谢huimeng。看过了，这是两年前的仓库。🤣

**Comment by PengXuanyao** [comment]
这个网站也不错哈：
* https://marklodato.github.io/visual-git-guide/index-en.html
* http://onlywei.github.io/explain-git-with-d3/#commit

**Comment by echo-hmwang** [comment]
> 这个网站也不错哈：
> 
> * https://marklodato.github.io/visual-git-guide/index-en.html
> * http://onlywei.github.io/explain-git-with-d3/#commit

3q. git我也是之前看的了，也已经不需要了🤣

**Comment by PengXuanyao** [comment]
提issue玩是吧😽，这是我收到的第一个issue

**Comment by echo-hmwang** [comment]
这也是我提的第一个issue🤣
